### ISSUE TITLE
Cannot start workbench in Linux

### ISSUE THREAD

**Issue by dipinknair** [ansys/pyworkbench#156]
``` python
from ansys.workbench.core import launch_workbench
wb = launch_workbench()
```
``` shell
Traceback (most recent call last):
  File "/home/staff/dkunhamb/pyansys/repos/pyworkbench/.env/lib/python3.10/site-packages/ansys/workbench/core/public_api.py", line 139, in __launch_server
    self._wmi_connection = wmi.WMI()
NameError: name 'wmi' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/staff/dkunhamb/pyansys/repos/pyworkbench/.env/lib/python3.10/site-packages/ansys/workbench/core/public_api.py", line 312, in launch_workbench
    return LaunchWorkbench(
  File "/home/staff/dkunhamb/pyansys/repos/pyworkbench/.env/lib/python3.10/site-packages/ansys/workbench/core/public_api.py", line 130, in __init__
    port = self.__launch_server(show_gui, host, version, server_workdir, username, password)
  File "/home/staff/dkunhamb/pyansys/repos/pyworkbench/.env/lib/python3.10/site-packages/ansys/workbench/core/public_api.py", line 218, in __launch_server
    except wmi.x_wmi:
NameError: name 'wmi' is not defined
```

It would be better to integrate `ansys.tools.path` for finding installed directory or supported versions.

**Comment by franknli** [comment]
Launching pywb server on a local Linux machine is now supported and should be available in release 0.9.

**Comment by dipinknair** [comment]
Reopening this because it still has limitation if user hasn't set env AWPROOT.
